// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// bind_list
List bind_list(List& L, int n_col, std::vector<std::string> col_classes);
RcppExport SEXP rmisc_bind_list(SEXP LSEXP, SEXP n_colSEXP, SEXP col_classesSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        List L = Rcpp::as<List >(LSEXP);
        int n_col = Rcpp::as<int >(n_colSEXP);
        std::vector<std::string> col_classes = Rcpp::as<std::vector<std::string> >(col_classesSEXP);
        List __result = bind_list(L, n_col, col_classes);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
